# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jennifer Griffith-Delgado
email: jennifer [dot] gd42 [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Practicing, reflecting, and learning about software engineering,
  among other technical things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jgriffith23.github.io" # the base hostname & protocol for your site
twitter_username: onegirlgeek
github_username:  jgriffith23

# Build settings
markdown: kramdown
