# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jennifer Griffith-Delgado
email: jennifer.gd42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a technical writer and editor, and I'm studying software
  engineering at Hackbright Academy. This blog is where I'm 
  documenting all the awesome stuff I learn!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jgriffith23.github.io" # the base hostname & protocol for your site
twitter_username: onegirlgeek
github_username:  jgriffith23

# Build settings
markdown: kramdown
